services:
  - type: web
    name: cathub-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    # 增加 worker 超时时间到 120 秒，增加 workers 数量
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 2 --threads 2 server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production

